### ISSUE TITLE
copying a tarball > 5G to s3 raises an exception and crashes the backup process

### ISSUE THREAD

**Issue by jnewland** [astrails/safe#10]
AWS::S3::EntityTooLarge should be rescued and either 1) warning printed indicating that the backup completed locally but could not be uploaded or 2) the file magically split into 5G chunks before upload

```
Your proposed upload exceeds the maximum allowed object size (AWS::S3::EntityTooLarge)
```

**Comment by astrails** [comment]
fixed in 0.2.6
