### ISSUE TITLE
Doesn't play nicely with symlinks

### ISSUE THREAD

**Issue by techiferous** [astrails/safe#11]
This either calls for a code change or a warning in the user documentation.  Details are explained in the "Update:" section of my blog post here:  http://techiferous.com/2009/11/backing-up-your-data-with-astrails-safe/

Thanks, by the way, for this awesome backup solution!

**Comment by astrails** [comment]
'tar' accepts 'options' just like mysql or pgdump.
you  can use "-h" to dereference symlinks:
    tar do
      options "-h"
      ...
    end

**Comment by techiferous** [comment]
Thanks!  I fixed my blog post about this issue.
