### ISSUE TITLE
0.2.7 doesn't rotate backups starting with :timestamp

### ISSUE THREAD

**Issue by jjjordan** [astrails/safe#20]
I'm running 0.2.7 and, with the paths that I've set up, it doesn't like deleting old backups from either S3 or local storage.  The default configurations worked but since I've changed the paths, it's broken.

One possible issue is that the 'tar' operation "fails" (some files in the paths I give it are inaccessible), but this doesn't stop the tarball from being created with everything I want to have in it.

My configuration file follows:

safe do
  local do
    path "/home/backup/local-backups/:timestamp/"
  end

  s3 do
    key "**_"
    secret "**_"
    bucket "***-backups"

```
path ":timestamp/"
```

  end

  gpg do
    options "--no-use-agent"
    command "/usr/bin/gpg"
    key "***"
  end

  keep do
    local 4
    s3 10
  end

  svndump do
    repo :repo do
      repo_path "/srv/svn/repo"
    end
  end

  tar do
    options "-h" # dereference symbolic links
    archive "config" do
      files ["/srv/svn/auth", "/srv/svn/_/_.authz"]
      # Note: a lot of these are protected, but get what we can.
      files ["/var/backups/*"]
      # ...
    end
  end
end

**Comment by ionelmc** [comment]
I got this problem too

**Comment by vitaly** [comment]
timestamp must be the last. the way it works is to 'get list of files by common prefix'
