### ISSUE TITLE
Error copying database "-" in the name

### ISSUE THREAD

**Issue by zar0ku1** [astrails/safe#34]
Specify the database in the configuration file:
###### 

```
mysqldump do
options "-ceKq --single-transaction --create-options"

user "test"
password "test"
socket "/var/run/mysqld/mysqld.sock"

database :db-test1
database :db-test2
 end
```
###### 

I have an error at start **astrails-safe -v -n astrails.conf**
###### 

/var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/builder.rb:19:in `method_missing': undefined local variable or method`test1' for #Astrails::Safe::Config::Builder:0xb6e06814 (NameError)
        from /home/zar0ku1/backup/astrails.conf:15
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:11:in `instance_eval'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:11:in`initialize'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:37:in `new'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:37:in`set'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/builder.rb:54:in `method_missing'
        from /home/zar0ku1/backup/astrails.conf:8
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:11:in`instance_eval'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:11:in `initialize'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe.rb:42:in`new'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe.rb:42:in `safe'
        from /home/zar0ku1/backup/astrails.conf:1
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/bin/astrails-safe:50:in`load'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/bin/astrails-safe:50:in `main'
        from /var/lib/gems/1.8/gems/astrails-safe-0.2.7/bin/astrails-safe:53
        from /usr/local/bin/astrails-safe:19:in`load'
        from /usr/local/bin/astrails-safe:19
######

**Comment by vitaly** [comment]
:db-test1 is an invalid Ruby syntax, and safe's configuration file is just ruby code.

use "db-test1" instead
