### ISSUE TITLE
no documentation for gzip-option

### ISSUE THREAD

**Issue by fwoeck** [astrails/safe#5]
There is no documentation for the gzip-option - or at least, I didn't find any.

**Comment by astrails** [comment]
there is no gzip option. gzip is automatic if no gpg encryption is used (which does its own compression)

**Comment by schorsch** [comment]
please add this to the readme

**Comment by invalidusrname** [comment]
I didn't realize this either. I think it would be helpful let people know gzip is used by default in the readme as well.
