### ISSUE TITLE
Is there a way to add support for FTP export ?

### ISSUE THREAD

**Issue by Sylvain** [astrails/safe#8]
I only can access to my backup server by ftp (same datacenter). it would be great to add ftp export. Is there a way to do this ? 

Many thanks by advance !

**Comment by astrails** [comment]
sure. just add another storage engine similar to S3 and Sftp. sources are quite simple and you only need to override a couple of functions. I suppose something like Net:Ftp might help you :)

**Comment by Sylvain** [comment]
Many thanks for your reply ! I manage to make FTP working ! I'm not sure if its is a good idea to commit this as I'm not a ruby developper, the code could have some bugs. Let me know if you want too see what I've done.

**Comment by astrails** [comment]
Ouch. Didn't see your reply... seems like it doesn't send notifications on replies to closed issues.
Anyway, please send your code :)
The best way is to fork safe on github and commit your changes into your repository.
Then send a 'pull' request.
Thanks for contributing .
